language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

before_script:
  - composer install --prefer-source

after_success:
  - travis_retry php vendor/bin/coveralls -v

before_install:
  - composer self-update
